using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.832
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("Mono.Sms")]
[assembly: AssemblyDescriptionAttribute("Aplicacion para el envio de mensajes de texto escrito en c#")]
[assembly: AssemblyCompanyAttribute("Mono.Sms Team")]
[assembly: AssemblyProductAttribute("Mono.Sms")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007 Dario Quintana and contributors. All Rights Reserved.")]
[assembly: AssemblyVersionAttribute("0.9.5")]