using System;
using System.Reflection;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("Mono.Sms")]
[assembly: AssemblyDescriptionAttribute("Aplicacion para el envio de mensajes de texto.")]
[assembly: AssemblyCompanyAttribute("Mono.Sms Team")]
[assembly: AssemblyProductAttribute("Mono.Sms")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007 Dario Quintana and contributors. All Rights Reserved.")]
[assembly: AssemblyVersionAttribute("0.9.0")]

